### ISSUE TITLE
[Help/Support] Audio hook/inject of a application

### ISSUE THREAD

**Issue by ghost** [lincolnfz/cefui#1]
Hi,

Read a bunch of code of you I found out ones that use Detours. So, I'm looking for an application/code/idea to hook/inject audio buffers of application on Windows 10 using Detours. Do you know something about this technique?

**Comment by lincolnfz** [comment]
the code can work on win10(x32)

2017-12-21 6:01 GMT+08:00 Daniel Felipe <notifications@github.com>:
